/*
----------------------------------------
	ELANG.H: MicroEMACS 3.10
----------------------------------------
*/

/*
----------------------------------------
	RCS id : $Header: f:/SALT/emacs/RCS/elang.h,v 1.6 1992/01/27 02:42:02 SALT Exp SALT $
----------------------------------------
*/

/*
----------------------------------------
	日本語メッセージ
----------------------------------------
*/

#define KTEX2 "テンポラリが作成できません"
#define KTEX3 "実行できませんでした"
#define KTEX6 "\r\n\n[終了]"
#define KTEX7 "行番号: "
#define KTEX8 "[中断]"
#define KTEX9 "マーク(%d)設定"
#define KTEX10 "マーク(%d)解除"
#define KTEX11 "マーク(%d)は未設定です"
#define KTEX12 "ヘルプが見付かりません"
#define KTEX13 ": describe-key "
#define KTEX15 ": bind-to-key "
#define KTEX16 "未定義の関数です"
#define KTEX17 "キー定義テーブルが一杯です"
#define KTEX18 ": unbind-key "
#define KTEX19 "未定義のキーです"
#define KTEX20 ": Apropos "
#define KTEX21 "キー定義リスト"
#define KTEX22 "キー定義リストを表示できません"
#define KTEX23 "キー定義リスト作成中..."
#define KTEX24 "バッファ"
#define KTEX26 "バッファ削除 "
#define KTEX28 "バッファ表示中"
#define KTEX29 "変更後のバッファ名: "
#define KTEX30 "状態  モード   サイズ バッファ名                      ファイル名"
#define KTEX35 "----  ------   ------ ----------                      ----------"
#define KTEX31 "         グローバルモード"
#define KTEX32 "変更点を破棄しますか"
#define KTEX33 "暗号化キー: "
#define KTEX34 "ファイル名: "
#define KTEX51 "変数名"
#define KTEX52 "'%s' は未定義です"
#define KTEX53 "値: "
#define KTEX54 "[マクロ中断]"
#define KTEX55 "表示する変数名"
#define KTEX56 "変数リスト"
#define KTEX57 "変数リストを表示できません"
#define KTEX58 "変数リスト作成中..."
#define KTEX59 "fill-column を %d にしました"
#define KTEX60 "%d/%d 行 %d/%d 桁 文字数 %D/%D (%d%%) 文字= 0x%x"
#define KTEX61 "不適切です"
#define KTEX62 "グローバルモード "
#define KTEX63 "モード "
#define KTEX64 "追加"
#define KTEX65 "削除"
#define KTEX66 "そのようなモードはありません"
#define KTEX67 "メッセージ: "
#define KTEX68 "挿入する文字列 <META>: "
#define KTEX69 "上書きする文字列 <META>: "
#define KTEX70 "[コピー]"
#define KTEX71 "再縮小はできません"
#define KTEX72 "最低一行は領域を指定して下さい"
#define KTEX73 "[縮小]"
#define KTEX74 "バッファは縮小されていません"
#define KTEX75 "[拡大]"
#define KTEX76 "マークは設定されていません"
#define KTEX77 "[BUG] マーク位置を見失いました"
#define KTEX78 "検索"
#define KTEX79 "見付かりません"
#define KTEX80 "検索文字列が設定されていません"
#define KTEX81 "逆方向検索"
#define KTEX84 "置換"
#define KTEX85 "確認置換"
#define KTEX86 "を"
#define KTEX87 "置換 '"
#define KTEX88 "' を '"
#define KTEX89 "[中断]"
#define KTEX90 "(Y)置換 (N)無視 (!)強行 (U)キャンセル (^G)中断 (.)戻る (?)ヘルプ: "
#define KTEX91 "[空白文字の置換] 中止します"
#define KTEX92 "%d 箇所 - 置換しました"
#define KTEX93 "削除エラー"
#define KTEX94 "メモリを使い尽くしました"
#define KTEX95 "%d とは何ですか？"
#define KTEX96 "[] 内に文字が指定されていません"
#define KTEX97 "[] が閉じていません"
#define KTEX98 "fill-column が設定されていません"
#define KTEX99 "メモリを使い尽くしました"
#define KTEX100 "%d 語 %d 文字 %d 行 一語当たりの平均文字数 %f"
#define KTEX101 "検索と行番号指定は同時にはできません"
#define KTEX102 "行番号が不明確です"
#define KTEX103 "%s 書込中"
#define KTEX104 "本当に終了しますか"
#define KTEX105 "マクロ記録中です"
#define KTEX106 "[マクロ記録開始]"
#define KTEX107 "マクロ記録中ではありません"
#define KTEX108 "[マクロ記録終了]"
#define KTEX109 "読み込み専用バッファです"
#define KTEX110 "コマンドが制限されています"
#define KTEX111 "マクロ番号が指定されていません"
#define KTEX112 "マクロ番号が範囲外です"
#define KTEX113 "マクロを設定できません"
#define KTEX114 "プロセデュア名: "
#define KTEX115 "実行するプロセデュア名: "
#define KTEX116 "存在しないプロセデュアです"
#define KTEX117 "実行するバッファ"
#define KTEX118 "存在しないバッファです"
#define KTEX119 "実行中にメモリーが不足しました"
#define KTEX120 "バッファ[%s] %d 行目: !BREAK が !WHILE ループの外にあります"
#define KTEX121 "バッファ[%s] %d 行目: 対応する !WHILE のない !ENDWHILE です"
#define KTEX122 "バッファ[%s] %d 行目: 対応する !ENDWHILE のない !WHILE です"
#define KTEX123 "バッファ[%s] %d 行目: マクロ実行中にメモリが不足しました"
#define KTEX124 "バッファ[%s] %d 行目: 未定義の制御構文です"
#define KTEX125 "バッファ[%s] %d 行目: マクロ登録中にメモリが不足しました"
#define KTEX126 "バッファ[%s] %d 行目: ループ内エラー"
#define KTEX127 "バッファ[%s] %d 行目: 未定義ラベルです"
#define KTEX128 "(E)式評価 (C/X)コマンド (T)追跡 (^G)中断 <SP>実行 <META>デバッグ中止"
#define KTEX129 "実行するファイル "
#define KTEX130 "マクロが定義されていません"
#define KTEX131 "ファイル差換 "
#define KTEX132 "ファイル挿入 "
#define KTEX133 "ファイル読込 "
#define KTEX134 "参照ファイル "
#define KTEX135 "既に存在します"
#define KTEX136 "バッファ名: "
#define KTEX137 "バッファを作れません"
#define KTEX138 "新規ファイル"
#define KTEX139 "読込中..."
#define KTEX140 "読込 "
#define KTEX141 "I/O エラー, "
#define KTEX142 "メモリ不足, "
#define KTEX143 " 行"
#define KTEX144 "書き出しファイル "
#define KTEX145 "ファイル名が指定されていません"
#define KTEX146 "不完全ファイルですが書き出しますか"
#define KTEX147 "縮小バッファですが書き出しますか"
#define KTEX148 "書き出し中..."
#define KTEX151 "ファイル名: "
#define KTEX152 "ファイルは存在しません"
#define KTEX153 "ファイル挿入中"
#define KTEX154 "挿入 "
#define KTEX155 "書き出しファイルをオープンできません"
#define KTEX156 "ファイルがクローズできません"
#define KTEX157 "書き出し I/O エラー"
#define KTEX158 "ファイル読込エラー"
#define KTEX159 "ファンクションキー番号が必要です"
#define KTEX160 "ファンクションキー番号が範囲外です"
#define KTEX161 "ラベル内容: "
#define KTEX162 " [Y/N]? "
#define KTEX164 "[検索中断]"
#define KTEX165 "インクリメンタルサーチ: "
#define KTEX166 "検索文字列が長すぎます"
#define KTEX167 "コマンドが長すぎます"
#define KTEX168 "文字列を挿入できません"
#define KTEX170 "[BUG] 文字挿入"
#define KTEX172 "上書き中にメモリが不足しました"
#define KTEX180 "読み込み専用ファイルです"
#define KTEX181 "ボリュームラベル、ディレクトリには書き込めません"
#define KTEX203 "ウィンドウ番号が範囲外です"
#define KTEX204 "このウィンドウは削除できません"
#define KTEX205 "%d 行のウィンドウは分割できません"
#define KTEX206 "ウィンドウは１つしかありません"
#define KTEX207 "できません"
#define KTEX208 "存在しないウィンドウです"
#define KTEX209 "画面サイズが範囲外です"
#define KTEX210 "画面幅が範囲外です"
#define KTEX211 "関数リスト"
#define KTEX212 "関数リストを表示できません"
#define KTEX213 "関数リスト作成中"
#define KTEX214 "%s は存在しません"
#define KTEX215 ": macro-to-key "
#define KTEX219 "[%s]"
#define KTEX220 "[META]"
#define KTEX221 "[CAPS ON]"
#define KTEX222 "[CAPS OFF]"
#define KTEX223 "不正な解像度です"
#define KTEX224 "検索中..."
#define KTEX225 "この画面モードではできません"
#define KTEX226 "ディレクトリ[%s]が見付かりません"
#define KTEX227 "ファイル名[%s]の指定に誤りがあります"
#define KTEX228 "バッファ[%s] %d 行目: エラーです [%s]"
#define KTEX229 ": zap-to-char "
#define KTEX230 "検索成功"
#define KTEX232 "環境変数名: "
#define KTEX233 "環境変数の設定に失敗しました"
#define KTEX234 "マクロを強制的に中断しました"
#define KTEX235 "処理を継続しますか"
#define KTEX236 "バッファ[%s]をセーブしますか"
#define KTEX237 "警告: メモリ限界の75%%に達しました"
#define KTEX238 "警告: メモリ限界の85%%に達しました"
#define KTEX239 "警告: メモリ限界の95%%に達しました"
#define KTEX240 "警告: 異常動作の可能性があります"
#define KTEX241 "[MALLOC] アボート: 内部エラー１"
#define KTEX242 "[MALLOC] アボート: 内部エラー２"
#define KTEX243 "[FREE] アボート: 内部エラー３"
#define KTEX244 "バッファ削除中..."
#define KTEX245 "ファイルが見付かりません"
#define KTEX247 "append-next-kill"
#define KTEX249 ": オートロード "
#define KTEX250 "バッファ[%s]がアクティブではありません"
#define KTEX251 "[読み込み中...  %d / %d bytes]"
#define KTEX252 "[書き出し中...  %d / %d bytes]"
#define KTEX253 "フォント [%s] が読めません"
#define KTEX254 "フォント読込 "
#define KTEX255 "ctrl-prefix の交換 (1) "
#define KTEX256 "ctrl-prefix の交換 (2) "
#define KTEX257 "%s と %s の ctrl-prefix を交換しました"
#define KTEX258 ": bind-to-xf%1d-key "
#define KTEX259 "対応する \\begin が見つかりません"
#define KTEX260 "LaTeX environment "
#define KTEX261 "} 括弧が見つかりません"
#define KTEX262 "違いがあります"
#define KTEX263 "同一のバッファです"
#define KTEX264 "２つのバッファに違いはありませんでした"
#define KTEX265 "%s %s %s (%s)  %s."
#define KTEX266 "[マーク %d / %d]"
#define KTEX267 "これ以上ユーザー変数を定義できません"
#define KTEX268 "ローカルキーバインド [%d]: "
#define KTEX269 "グローバルキーバインド: "
#define KTEX270 "シンボリックリンク名が長すぎます"

#define KTEX300 " 終了."
#define KTEX301 " ..."
#define KTEX302 "ディレクトリ読み込み中 %s%s%s"
#define KTEX303 "ファイルコピー %s%s"
#define KTEX304 "ファイル移動 %s%s"
#define KTEX305 "パス名 "
#define KTEX306 "コピー先 "
#define KTEX307 "移動先 "
#define KTEX308 "ディレクトリ名: "
#define KTEX309 "ディレクトリ、ボリューム、システムファイルはマークできません "
#define KTEX310 "マークされたファイルはありません "
#define KTEX311 "%s はディレクトリではありません"
#define KTEX312 "TRASH を空にします"
#define KTEX313 "ファイル消去 %s%s"
#define KTEX314 "コマンドの実行に失敗しました [%s %s %s]"
#define KTEX315 "同じ名前のファイルがあります [%s] (O/S/T/!/#/?) : "
#define KTEX316 "同じ名前のディレクトリがあるので無視します [%s] "
#define KTEX317 "ディスクの容量が足りません"
#define KTEX318 "マークしたファイルを対象リストから外しましす"
#define KTEX319 "ディレクトリが見つかりません。 ディレクトリを作成しますか"
#define KTEX320 "DIRED モードが設定されていません"
#define KTEX321 "同じディレクトリです"
#define KTEX322 "マークする拡張子: "
#define KTEX323 "ディレクトリ名が正しくありません %s"
#define KTEX324 "ディレクトリが見つかりません %s"
#define KTEX325 "(O)上書き (S)無視 (T)時刻 (!)上書き強行 (#)時刻強行 (?)ヘルプ: "
#define KTEX326 "ファイルを消去しますか"

/*
----------------------------------------
	英語メッセージ
----------------------------------------
*/

#define TEXT34 "File: "
